/**
 * /go/<slug> — short-link redirector for shareable contexts.
 *
 * Resolution order (first match wins):
 *
 *   1. Affiliate link  — looked up against the affiliateLink Sanity
 *      collection by slug. Applies the program's tracking ID + region
 *      swap (Amazon storefront, Backcountry US ↔ Bergfreunde EU, etc.)
 *      based on x-vercel-ip-country at request time. This is the path
 *      that PDFs hit (the cheat sheet generated by the publish script).
 *
 *   2. Curated short link — defined in CURATED below. Hand-pick the
 *      destination + UTMs for each. Stable URLs you can put on print
 *      that never break.
 *
 *   3. Guide passthrough — any slug that matches a published guide
 *      slug redirects to /guides/<slug> with sensible UTM defaults.
 *
 *   4. Fallback — unknown slugs 302 to the homepage with
 *      utm_campaign=unknown-<slug> so we can detect mistyped / abused
 *      links in analytics.
 *
 * SEO: returns 302 (temporary) so Google doesn't pass /go/* link-juice
 * into the destination — that's intentional, /go/ is for outbound
 * campaign traffic, not a canonical path. Robots.txt should disallow
 * /go/ if we want to be extra-safe.
 */
import { NextResponse } from "next/server";
import { buildUtmUrl } from "../../_lib/utm";
import { client } from "../../../sanity/lib/client";
import {
  resolveRegionalLink,
  withAffiliateParams,
  resolveAmazonRegional,
} from "../../_lib/affiliatePrograms";

const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_URL || "https://testedroutes.com";

/**
 * Curated short links. Add entries as campaigns require them.
 * The key is the slug after /go/; the value is the full destination
 * with UTMs already baked in (use buildUtmUrl in code, not here).
 *
 * Convention: keep slugs lowercase, hyphenated, short. Once published,
 * treat them as stable — printed media relies on them not changing.
 */
const CURATED = {
  // Seychelles 7-day guide — downloadable Google My Map (beaches, food,
  // hotels, ferries). External My Maps link, so no UTMs to bake in.
  "seychelles-map":
    "https://www.google.com/maps/d/viewer?mid=1EdUP3XbOOmub6TE5IM-6sC7K_SJa-3g",

  // Iceland. Pin-level slugs (iceland-<pinid>) live in Sanity via
  // sync_go_links from the country master; these are the extra print slugs
  // with no master row. Maps place-card searches are deliberate v1
  // destinations — re-point per venue in Studio when providers are picked.
  //
  // Namespacing rule, now that Iceland is a multi-guide country: anything
  // that differs per itinerary is guide-scoped (iceland-7d-*), because the
  // 5-day South Coast and the layover decks will each ship their own My Map
  // and would otherwise collide on a slug that is already in print. Places
  // and services stay country-scoped (iceland-car, iceland-drangar) so a pin
  // reprinted in six guides keeps one slug and one destination to re-point.
  "iceland-7d-map":
    "https://www.google.com/maps/d/viewer?mid=1By0oiIG4vTBy-5NorrCBvuyhXXbfAjg",
  "iceland-7d-hotels":
    "https://www.google.com/maps/d/viewer?mid=1By0oiIG4vTBy-5NorrCBvuyhXXbfAjg",
  "iceland-car":
    "https://www.google.com/maps/search/?api=1&query=Car%20rental%20Keflavik%20Airport",
  "iceland-grillmarkadurinn":
    "https://www.google.com/maps/search/?api=1&query=Grillmarkadurinn%20Reykjavik",
  "iceland-drangar":
    "https://www.google.com/maps/search/?api=1&query=Drangar%20restaurant%20Hotel%20Kria%20Vik",
  "iceland-black-crust":
    "https://www.google.com/maps/search/?api=1&query=Black%20Crust%20Pizzeria%20Vik",

  // Triftbrücke day-trip guide — QR targets, mirrors the guide's meta.yaml
  // reservations. Printed in the PDF: treat every slug as frozen.
  "trift-gondola": "https://www.grimselwelt.ch/en/railways/triftbahn/",
  "trift-parking":
    "https://www.google.com/maps/search/?api=1&query=46.721194%2C8.318272",
  "trift-picnic":
    "https://www.google.com/maps/search/?api=1&query=47.37785%2C8.53991",
  "trift-dinner": "https://www.hotelterrasse.ch/",
  "trift-windegg": "https://www.windegghuette.ch/reservation",
  "trift-sbb-saver": "https://www.sbb.ch/en/offers/saver-day-pass",
  "trift-meteoswiss": "https://www.meteoswiss.admin.ch/",
  "trift-sbb-app": "https://www.sbb.ch/en/",
  "trift-schweizmobil": "https://schweizmobil.ch/en/",
  "trift-map":
    "https://www.google.com/maps/d/viewer?mid=1aDbc_78_MSJ8geLTnmdW7FRQn_F4QBM",

  // Simplon–Saas Fee weekend-hike guide — QR targets printed in the PDF:
  // treat every slug as frozen.
  "ssf-hotel": "https://www.alpenblick-gspon.ch/",
  "ssf-sbb": "https://www.sbb.ch/en/offers/saver-day-pass",
  "ssf-mob": "https://schweizmobil.ch/en/",
  "ssf-bristol": "https://www.hotel-bristol-saas-fee.ch/en/",
  "ssf-blackrock": "https://maps.app.goo.gl/FLUdPqwg6hmUexA38",
  "ssf-killerhof": "https://maps.app.goo.gl/5xFsTgcM2RcT3XA19",
  "ssf-gondola": "https://staldenried.ch/lssg/",
  "ssf-parkrail": "https://www.sbb.ch/en/offers/car-parking",
  "ssf-car": "https://www.sixt.ch/",
  "ssf-meteo": "https://www.meteoswiss.admin.ch/",
  "ssf-map":
    "https://www.google.com/maps/d/viewer?mid=10U8OPYSeOVbggFoz9Fatkp1oYQbqCqc",

  // Saas Fee–Gruben weekend-hike guide (Alpine Passes Trail stages 20+21)
  // — QR targets printed in the PDF: treat every slug as frozen.
  "sfg-hotel-graechen": "https://www.hotel-walliserhof.ch/",
  "sfg-hotel-gruben": "https://www.hotelschwarzhorn.ch/",
  "sfg-hotel-backup": "https://www.hannigalp.ch/",
  "sfg-sbb": "https://www.sbb.ch/en/offers/saver-day-pass",
  "sfg-parkrail": "https://www.sbb.ch/en/offers/car-parking",
  "sfg-jungenbahn": "https://www.jungeralp.ch/jungenbahn",
  "sfg-hannigalpbahn": "https://graechen.ch/en/Info-service/Lift-Info",
  // turtmanntal.ch was rebuilt mid-2026; the old /site/gruben-meiden/anreise 404s.
  "sfg-bus": "https://turtmanntal.ch/infocenter/",
  "sfg-meteo": "https://www.meteoswiss.admin.ch/",
  "sfg-mob": "https://schweizmobil.ch/en/",
  "sfg-map":
    "https://www.google.com/maps/d/viewer?mid=1qpEaRI_jwTY1bZRdgLCk6c6tBFsRhCI",

  // Gruben–Grimentz weekend-hike guide (Alpine Passes Trail stages 22+23)
  // — QR targets printed in the PDF: treat every slug as frozen.
  "ggr-hotel": "https://www.weisshorn.ch/",
  "ggr-hotel-gruben": "https://www.hotelschwarzhorn.ch/",
  "ggr-hotel-backup": "https://cabanebellatola.ch/en/",
  "ggr-hotel-stluc": "https://bellatola.ch/",
  "ggr-sbb": "https://www.sbb.ch/en/offers/saver-day-pass",
  "ggr-parkrail": "https://www.sbb.ch/en/offers/car-parking",
  "ggr-funi": "https://tignousa.ch/en/practical-information/",
  // turtmanntal.ch was rebuilt mid-2026; the old /site/gruben-meiden/anreise 404s.
  // InfoCenter page hosts the current-year Bahn+Bus Fahrplan PDF and the phone number.
  "ggr-bus": "https://turtmanntal.ch/infocenter/",
  "ggr-meteo": "https://www.meteoswiss.admin.ch/",
  "ggr-mob": "https://schweizmobil.ch/en/",
  "ggr-map":
    "https://www.google.com/maps/d/viewer?mid=1KO8J6IfOVZqT83JReUuIoaO7CN7EqzE",

  // Grimentz–Evolène weekend-hike guide (Alpine Passes Trail stages 24+25)
  // — QR targets printed in the PDF: treat every slug as frozen.
  "gev-hut": "https://www.cabanedesbecs.ch/en/pages/18-tarifs-et-reservations",
  "gev-sbb": "https://www.sbb.ch/en/offers/saver-day-pass",
  "gev-parkrail": "https://www.sbb.ch/en/offers/car-parking",
  // Official 2026 line-381 timetable PDF — URL changes each December;
  // re-point when the new Jahresfahrplan is published.
  "gev-bus": "https://widgets.oev-info.ch/publikation/jahresfpl/12.381.pdf",
  "gev-meteo": "https://www.meteoswiss.admin.ch/",
  "gev-mob": "https://schweizmobil.ch/en/",
  "gev-gondola":
    "https://bike-grimentz-zinal.ch/en/activities-in-anniviers/grimentzzinal/ski-lifts",
  "gev-hotel-backup": "https://hotel-grimentz.ch/en/",
  "gev-taverne":
    "https://www.valdherens.ch/en/cafe-restaurant-la-taverne-evolenarde-fp31995",
  "gev-hotel-evolene":
    "https://www.valdherens.ch/en/hotel-restaurant-eden-fp45317",
  "gev-map":
    "https://www.google.com/maps/d/viewer?mid=1NlXJH6zVRjVrZNJ6ehuEuC5SFQnfGA8",

  // Switzerland-evergreen QR targets, shared across all guides from the
  // stages 1-6 builds onward (founder decision 2026-08-07). One QR asset,
  // one slug, every Swiss deck. Earlier guides (ssf/sfg/ggr/gev) keep
  // their per-guide slugs — those PDFs are printed and frozen.
  "ch-sbb": "https://www.sbb.ch/en/offers/saver-day-pass",
  "ch-parkrail": "https://www.sbb.ch/en/offers/car-parking",
  "ch-meteo": "https://www.meteoswiss.admin.ch/",
  "ch-mob": "https://schweizmobil.ch/en/",

  // St. Moritz–Alp Flix weekend-hike guide (Alpine Passes Trail stages 1+2)
  // — QR targets printed in the PDF: treat every slug as frozen.
  "sma-hut": "https://www.chamannajenatsch.ch/en/online-reservation/",
  // Bus Alpin shuttle Sur ⇄ Alp Flix (line 90.188) — season page with times.
  "sma-bus": "https://busalpin.ch/regionen/alp-flix/sommer/",
  // Official 2026 line-182 (Julier PostBus) timetable PDF — URL changes each
  // December; re-point when the new Jahresfahrplan is published.
  "sma-postbus": "https://widgets.oev-info.ch/publikation/jahresfpl/90.182.pdf",
  // Corviglia funicular is closed summer 2026: lift access is the Signal
  // cable car from St. Moritz Bad — tickets page covers fares + times.
  "sma-lift": "https://www.mountains.ch/en/tickets/",
  "sma-hotel-backup": "https://www.flix.ch/",
  "sma-stmoritz": "https://www.stmoritz.com/en/",
  "sma-map":
    "https://www.google.com/maps/d/viewer?mid=1vmowovap0e53bU-ZX6PKMkQCUUUvXVA",

  // Alp Flix–Ausserferrera weekend-hike guide (Alpine Passes Trail stages 3+4)
  // — QR targets printed in the PDF: treat every slug as frozen.
  // pizmitgel.ch was unreachable at build time (2026-08-07) — the official
  // Val Surses listing page is the stable target.
  "afa-hotel": "https://www.valsurses.ch/en/hotel-piz-mitgel",
  "afa-alp": "https://alp-derr.ch/",
  // Official 2026 line-552 (Juf–Andeer PostBus) timetable PDF — URL changes
  // each December; re-point when the new Jahresfahrplan is published.
  "afa-bus": "https://widgets.oev-info.ch/publikation/jahresfpl/90.552.pdf",
  // Bus Alpin shuttle Sur ⇄ Alp Flix (line 90.188) — season page with times.
  "afa-shuttle": "https://busalpin.ch/regionen/alp-flix/sommer/",
  "afa-hotel-backup": "https://www.valsurses.ch/en/hotel-restaurant-aves",
  "afa-edelweiss": "https://www.valferrera.com/",
  "afa-taverna": "https://www.pizzeriataverna.ch/",
  "afa-map":
    "https://www.google.com/maps/d/viewer?mid=12Lj_wGJrJ9aL0r-5IGYzxl2PWwyhGHY",

  // Ausserferrera–Turra weekend-hike guide (Alpine Passes Trail stages 5+6)
  // — QR targets printed in the PDF: treat every slug as frozen.
  "atu-hotel": "https://www.hotel-bodenhaus.ch/",
  "atu-turrahus": "https://www.turrahus.ch/",
  // Official 2026 line-401 (Safiental PostBus) timetable PDF — URL changes
  // each December; re-point when the new Jahresfahrplan is published.
  "atu-bus": "https://widgets.oev-info.ch/publikation/jahresfpl/90.401.pdf",
  // Wanderbus Splügen–Alp Stutz (reservation required) — Beverin park page.
  "atu-wanderbus": "https://naturpark-beverin.ch/de/wanderbus",
  // piz-tambo.ch was unreachable at build time (2026-08-07) — regional
  // accommodation directory is the stable backup-beds target.
  "atu-hotel-backup": "https://en.viamala.ch/accommodation",
  "atu-volg": "https://www.volg.ch/standorte-oeffnungszeiten/",
  "atu-map":
    "https://www.google.com/maps/d/viewer?mid=1b-S1EZldvz5kJ0849lKsB-niJipJPrk",

  // "podcast": buildUtmUrl(`${SITE_ORIGIN}/subscribe`, {
  //   source: "shortlink", medium: "podcast", campaign: "podcast-mention-2026",
  // }),
};

/**
 * Look up an affiliateLink by slug. Returns null if not found.
 * Cached per request — Sanity CDN handles the rest.
 */
async function loadAffiliateLink(slug) {
  try {
    return await client.fetch(
      `*[_type == "affiliateLink" && slug.current == $slug][0]{
        _id,
        label,
        "slug": slug.current,
        category,
        url,
        program,
        regions[]{ region, url, program }
      }`,
      { slug },
    );
  } catch {
    return null;
  }
}

async function isPublishedGuide(slug) {
  try {
    const { loadGuideBySlug } = await import("../../_lib/loadGuides");
    const guide = await loadGuideBySlug(slug);
    return !!guide;
  } catch {
    return false;
  }
}

/**
 * Build the final tracked redirect URL for an affiliateLink, applying
 * the right region override + tracking-ID injection.
 */
function buildAffiliateRedirect(link, country) {
  if (!link) return null;
  const resolved = resolveRegionalLink(link, country);
  if (!resolved?.url) return null;

  // Amazon: regional storefront + tag swap from the .com URL the
  // editor pasted as the default. (Authors don't have to manage
  // .co.uk / .de URLs separately.)
  if (resolved.program === "amazon") {
    return resolveAmazonRegional(resolved.url, country);
  }

  // Everything else: append the simple tracking param if the program
  // takes one and the env var is set; pass-through otherwise.
  return withAffiliateParams(resolved.url, resolved.program, country);
}

export async function GET(request, { params }) {
  const { slug: rawSlug } = await params;
  const slug = String(rawSlug || "").toLowerCase().trim();
  if (!slug) {
    return NextResponse.redirect(SITE_ORIGIN, { status: 302 });
  }

  // Vercel injects x-vercel-ip-country. In dev / non-Vercel envs it's
  // missing — falls back to the .com / default region.
  const country = request.headers.get("x-vercel-ip-country") || null;

  // 1. Affiliate link
  const affiliate = await loadAffiliateLink(slug);
  if (affiliate) {
    const target = buildAffiliateRedirect(affiliate, country);
    if (target) {
      return NextResponse.redirect(target, { status: 302 });
    }
  }

  // 2. Curated short link
  if (CURATED[slug]) {
    return NextResponse.redirect(CURATED[slug], { status: 302 });
  }

  // 3. Guide passthrough
  if (await isPublishedGuide(slug)) {
    const target = buildUtmUrl(`${SITE_ORIGIN}/guides/${slug}`, {
      source: "shortlink",
      medium: "referral",
      campaign: slug,
    });
    return NextResponse.redirect(target, { status: 302 });
  }

  // 4. Unknown — fall through to homepage with a tagged "unknown-<slug>"
  // campaign so we can spot mistyped / abused short links in analytics.
  const fallback = buildUtmUrl(SITE_ORIGIN, {
    source: "shortlink",
    medium: "referral",
    campaign: `unknown-${slug.slice(0, 40)}`,
  });
  return NextResponse.redirect(fallback, { status: 302 });
}
