/**
 * /go/<slug> — short-link redirector for shareable contexts.
 *
 * Resolution order (first match wins):
 *
 *   1. Affiliate link  — looked up against the affiliateLink Sanity
 *      collection by slug. Applies the program's tracking ID + region
 *      swap (Amazon storefront, Backcountry US ↔ Bergfreunde EU, etc.)
 *      based on x-vercel-ip-country at request time. This is the path
 *      that PDFs hit (the cheat sheet generated by the publish script).
 *
 *   2. Curated short link — defined in CURATED below. Hand-pick the
 *      destination + UTMs for each. Stable URLs you can put on print
 *      that never break.
 *
 *   3. Guide passthrough — any slug that matches a published guide
 *      slug redirects to /guides/<slug> with sensible UTM defaults.
 *
 *   4. Fallback — unknown slugs 302 to the homepage with
 *      utm_campaign=unknown-<slug> so we can detect mistyped / abused
 *      links in analytics.
 *
 * SEO: returns 302 (temporary) so Google doesn't pass /go/* link-juice
 * into the destination — that's intentional, /go/ is for outbound
 * campaign traffic, not a canonical path. Robots.txt should disallow
 * /go/ if we want to be extra-safe.
 *
 * Analytics: this route is the only place a printed QR code touches our
 * infrastructure. The redirect completes before any browser JS exists, so
 * a client-side tracker can never see these — an anonymous server capture
 * is the only way to know which QRs readers actually scan in the field,
 * and it is what turns the reservation links in a PDF into a signal about
 * which parts of a guide get used.
 */
import { NextResponse, after } from "next/server";
import { buildUtmUrl } from "../../_lib/utm";
import { CURATED } from "../../_lib/curatedGoLinks";
import { captureServer, requestContext } from "../../_lib/serverAnalytics";
import { client } from "../../../sanity/lib/client";
import {
  resolveRegionalLink,
  withAffiliateParams,
  resolveAmazonRegional,
} from "../../_lib/affiliatePrograms";

const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_URL || "https://testedroutes.com";

// Curated short links live in app/_lib/curatedGoLinks.js (shared with the
// weekly link monitor); the conventions and per-guide history are
// documented there. Frozen once printed.

/**
 * Look up an affiliateLink by slug. Returns null if not found.
 * Cached per request — Sanity CDN handles the rest.
 */
async function loadAffiliateLink(slug) {
  try {
    return await client.fetch(
      `*[_type == "affiliateLink" && slug.current == $slug][0]{
        _id,
        label,
        "slug": slug.current,
        category,
        url,
        program,
        regions[]{ region, url, program }
      }`,
      { slug },
    );
  } catch {
    return null;
  }
}

async function isPublishedGuide(slug) {
  try {
    const { loadGuideBySlug } = await import("../../_lib/loadGuides");
    const guide = await loadGuideBySlug(slug);
    return !!guide;
  } catch {
    return false;
  }
}

/**
 * Build the final tracked redirect URL for an affiliateLink, applying
 * the right region override + tracking-ID injection.
 */
function buildAffiliateRedirect(link, country) {
  if (!link) return null;
  const resolved = resolveRegionalLink(link, country);
  if (!resolved?.url) return null;

  // Amazon: regional storefront + tag swap from the .com URL the
  // editor pasted as the default. (Authors don't have to manage
  // .co.uk / .de URLs separately.)
  if (resolved.program === "amazon") {
    return resolveAmazonRegional(resolved.url, country);
  }

  // Everything else: append the simple tracking param if the program
  // takes one and the env var is set; pass-through otherwise.
  return withAffiliateParams(resolved.url, resolved.program, country);
}

/**
 * Redirect, and record the scan without making the reader wait for it.
 *
 * `after()` runs the capture once the 302 is already on its way, which
 * matters more here than anywhere else on the site: somebody is standing at
 * a trailhead with one bar of signal, and the whole promise of a printed QR
 * is that it resolves instantly. Fire-and-forget without `after()` would be
 * worse than useless — a serverless function is frozen the moment it
 * responds, so a floating promise is dropped rather than delivered, and it
 * would be dropped most often on exactly the slow connections we would most
 * want to hear about.
 *
 * `kind` records which of the four resolution branches matched. It's the
 * difference between "the Saas-Fee hotel QR gets scanned a lot" and "people
 * keep hitting a slug we never registered".
 */
function redirectWith(request, { slug, kind, target }) {
  let targetHost = null;
  try {
    targetHost = new URL(target).host || null;
  } catch {
    // CURATED entries are hand-written; a malformed one shouldn't 500 the
    // redirect, it should just lose one analytics dimension.
  }
  after(
    captureServer("go_link_click", {
      slug,
      kind,
      target_host: targetHost,
      ...requestContext(request),
    }),
  );
  return NextResponse.redirect(target, { status: 302 });
}

export async function GET(request, { params }) {
  const { slug: rawSlug } = await params;
  const slug = String(rawSlug || "").toLowerCase().trim();
  if (!slug) {
    return NextResponse.redirect(SITE_ORIGIN, { status: 302 });
  }

  // Vercel injects x-vercel-ip-country. In dev / non-Vercel envs it's
  // missing — falls back to the .com / default region.
  const country = request.headers.get("x-vercel-ip-country") || null;

  // 1. Affiliate link
  const affiliate = await loadAffiliateLink(slug);
  if (affiliate) {
    const target = buildAffiliateRedirect(affiliate, country);
    if (target) {
      return redirectWith(request, { slug, kind: "affiliate", target });
    }
  }

  // 2. Curated short link
  if (CURATED[slug]) {
    return redirectWith(request, { slug, kind: "curated", target: CURATED[slug] });
  }

  // 3. Guide passthrough
  if (await isPublishedGuide(slug)) {
    const target = buildUtmUrl(`${SITE_ORIGIN}/guides/${slug}`, {
      source: "shortlink",
      medium: "referral",
      campaign: slug,
    });
    return redirectWith(request, { slug, kind: "guide", target });
  }

  // 4. Unknown — fall through to homepage with a tagged "unknown-<slug>"
  // campaign so we can spot mistyped / abused short links in analytics.
  const fallback = buildUtmUrl(SITE_ORIGIN, {
    source: "shortlink",
    medium: "referral",
    campaign: `unknown-${slug.slice(0, 40)}`,
  });
  // Worth watching in the digest: a printed slug that never got registered
  // shows up here as repeat traffic, and every one of those is a reader who
  // scanned a code in a guide they paid for and landed nowhere useful.
  return redirectWith(request, {
    slug: slug.slice(0, 80),
    kind: "unknown",
    target: fallback,
  });
}
