// UI strings: lt. One locale per module so client components can import
// a single language (or none) instead of the whole five-locale registry.
const lt = {
  nav: {
    destinations: "Kryptys",
    guides: "Gidai",
    inspire: "Įkvėpimas",
    aboutMe: "Apie mane",
    explore: "Naršyti",
    about: "Apie",
  },
  inspireList: {
    title: "Tikros kelionės. Tikros pamokos",
    subtitle: "Istorijos kitai jūsų kelionei įkvėpti",
    searchPlaceholder: "Ieškoti istorijų – pabandykite 'ledynas' arba 'persėdimas'",
    searchButton: "Ieškoti",
    heading: "Kelionės, o ne tik įrašai",
    story: "istorija",
    stories: "istorijos",
    noMatchTitle: "Atitinkančių kelionių nerasta",
    noMatchBody: "Pabandykite trumpesnę frazę arba išvalykite paiešką.",
    clearSearch: "Išvalyti paiešką",
    guideBadge: "Gidas",
    familyBadge: "Šeimai",
    credibility: [
      "140+ šalių",
      "15+ metų savarankiško keliavimo patirties",
      "Įkopta į 5 iš 7 viršukalnių",
      "Maršrutai išbandyti tikrose kelionėse",
    ],
    collectionsHeading: "Naršykite pagal kelionės tipą",
    viewCollection: "Žiūrėti kolekciją",
    collections: [
      {
        title: "Alpių dienos Šveicarijoje",
        intro:
          "Struktūruotos dienos išvykos iš Ciuricho – Alpių peizažai, aiški transporto logika ir realistiškas tempas.",
      },
      {
        title: "Savarankiški maršrutai po šalis",
        intro:
          "Ilgesni maršrutai, sudėlioti pagal eigą, logistiką ir tai, kas iš tikrųjų veikia vietoje.",
      },
      {
        title: "Ekstremalios patirtys",
        intro:
          "Patirtys, kurios formuoja, kaip maršrutai kuriami ir išbandomi realiame pasaulyje.",
      },
      {
        title: "Ekspedicijų maršrutai",
        intro:
          "Ilgos kelionės, kurias lemia sausumos logistika, sudėtingos sienos ir neapibrėžtumas.",
      },
    ],
    howITestTitle: "Kaip išbandau savo gidų maršrutus",
    howITestBody:
      "Maršrutų nekuriu prie stalo. Išbandau juos vietoje – aukštis, logistika, reljefas ir tikras neapibrėžtumas.",
    extremeLabels: [
      "Bėgimas su buliais | Ispanija",
      "Nardymas su rykliais | Fidžis",
      "Lentos nuo ugnikalnio | Nikaragva",
      "Šuoliai parašiutu ir parasparniai | Brazilija",
      "Kopimas ledu | Italija",
      "Geležies rūdos traukinys | Mauritanija",
      "Viršukalnės | Aliaska",
      "Atokūs kirtimai | Vakarų Afrika",
    ],
    ctaTitle: "Pasiruošę įkvėpimą paversti tikru maršrutu?",
    ctaBody:
      "Aukščiausios kokybės gidai, gimę iš 15 metų savarankiškų kelionių po 140 šalių.",
    browseGuides: "Naršyti gidus →",
    emptyTitle: "Vertimai jau pakeliui",
    emptyBody: "Šios istorijos jau yra anglų kalba – vertimai netrukus.",
    emptyLink: "Skaityti angliškai →",
    readStory: "Skaityti istoriją",
  },
  story: {
    quickFacts: "Trumpai",
    bestSeason: "Geriausias metas:",
    fullGuideChip: "Yra pilnas gidas ↓",
    planningTrip: "Planuojate šią kelionę?",
    planningBody:
      "Pilname gide – maršrutas, logistika, išlaidos, rezervacijų nuorodos ir laikai: viskas, ko reikia susiplanuoti patiems.",
    readFullGuide: "Žiūrėti gidą →",
    browseAllGuides: "Žiūrėti visus gidus →",
    moreFrom: "Daugiau iš {country}",
    exploreDestination: "Atrasti {country} →",
    turnInspiration: "Paverskite įkvėpimą planu",
    guidesCardTitle: "TestedRoutes Guides",
    guidesCardBody:
      "Kelionėse išbandyti gidai, gimę iš 15 metų savarankiško keliavimo. PDF formatas, veikia be interneto.",
    endCtaTitle: "Patiko istorija? Maršrutas jau suplanuotas.",
    endCtaBody:
      "Įsigykite išbandytą šios kelionės gidą – tikslus maršrutas, rezervacijos, išlaidos ir laikai viename PDF.",
    gallery: "Galerija",
    guidesForTrip: "Šios kelionės gidai",
  },
  guideList: {
    title: "Gidai",
    tagline: "Atsispausdinkite, sekite – kelionė pavyks.",
    heading: "Kelionėse išbandyti gidai",
    browseHeading: "Naršyti gidus",
    filterType: "Kelionės tipas",
    filterCountry: "Šalis",
    filterAll: "Visi",
    filterLength: "Trukmė",
    filterActivity: "Veikla",
    filterSeason: "Sezonas",
    typeCountry: "Įveskite šalį…",
    mostGuides: "Daugiausia gidų",
    allOfContinent: "Visa {name}",
    allCountries: "Visos šalys",
    countriesWord: "šalys",
    trust: [
      { title: "Nueita savomis kojomis", body: "Išbandyta vietoje, ne prie ekrano" },
      { title: "Sukurta kelionei", body: "Vienas PDF, veikia be interneto, nereikia programėlės" },
      { title: "Tikri skaičiai", body: "Kainos, laikai ir logistika, kurie sutampa" },
    ],
    testedBy: "Išbandė",
    credentials: "140 šalių",
    guide: "gidas",
    guides: "gidai",
    pdfGuide: "PDF gidas",
    purchased: "nupirkta",
    from: "Nuo",
    viewGuide: "Žiūrėti gidą",
    buyGuide: "Pirkti gidą",
    searchPlaceholder: "Ieškoti gidų…",
    comingSoon: "Netrukus",
    metaDescription:
      "Kiekvienas gidas – tikras, kelionėje išbandytas maršrutas. Nusipirkite kartą, sekite žingsnis po žingsnio.",
  },
  guide: {
    metaDescPrefix: "Savarankiškos kelionės gidas:",
    viewAllPhotos: "Žiūrėti viską",
    readFullStory: "Skaityti visą istoriją →",
    tripDetails: "Kelionės detalės",
    lastReviewed: "Paskutinė peržiūra",
    location: "Vieta",
    startingPoint: "Starto taškas",
    stop: "Stotelė",
    destination: "Tikslas",
    finish: "Finišas",
    whyThisTrip: "Kodėl ši kelionė",
    whoThisIsFor: "Kam ji skirta",
    notSuitable: "Netinka",
    whatYouGet: "Ką gausite",
    affiliateHeading: "Partnerių nuorodos.",
    affiliateBody:
      "Kai kurios nuorodos žemiau yra partnerių nuorodos. Perkant per jas gauname nedidelį komisinį – jums tai nieko papildomai nekainuoja. Kaip „Amazon Associate“, TestedRoutes uždirba iš tinkamų pirkimų.",
    affiliateMore: "Daugiau apie tai, kaip tai veikia",
    myExperience: "Mano patirtis",
    continuesInFull: "Tęsinys pilname gide",
    wantFullPlan: "Norite viso plano?",
    pdfIncludes:
      "PDF gide – planas kiekvienai dienai, transporto laikai, rezervacijų nuorodos ir oro taisyklės. Atsisiuntimas iškart po pirkimo.",
    getFullGuide: "Gauti pilną gidą",
    readersSay: "Ką sako skaitytojai",
    saveTime: "Taupykite laiką ir pinigus",
    guidedTour: "Ekskursija su gidu",
    fixedSchedule: "Fiksuotas grafikas · Grupės tempas",
    planYourself: "Planuoti patiems",
    hoursPlus: "8+ valandų",
    researchRisk: "Paieškos · Spragų rizika",
    thisGuide: "Šis gidas",
    thirtyMin: "30 min · Pilnas maršrutas",
    faqTitle: "Dažni klausimai",
    faq: [
      {
        question: "Ar šis gidas atnaujintas?",
        answer:
          "Taip. Kiekvienas TestedRoutes gidas reguliariai peržiūrimas – data kelionės detalių viršuje rodo paskutinę peržiūrą. Peržiūrose tikrinamos neveikiančios rezervacijos, transporto pakeitimai, kainos ir sezoniniai uždarymai, kad gidas išliktų tikslus.",
      },
      {
        question: "Kokiu formatu gaunu gidą?",
        answer:
          "PDF, atsisiunčiamas iškart po pirkimo. Išsaugotas telefone, planšetėje ar kompiuteryje veikia be interneto – jokios programėlės nereikia.",
      },
      {
        question: "O jei mano dieną bus prastas oras?",
        answer:
          "Gide yra go/no-go sprendimų taisyklės ir nuo oro priklausančios alternatyvos, kur jos egzistuoja. Jei kelionė visiškai priklauso nuo oro ir jūsų datos netinka, per 30 dienų paprašykite pinigų grąžinimo.",
      },
      {
        question: "Ar galiu susigrąžinti pinigus, jei netiks?",
        answer:
          "Taip – 30 dienų, be klausimų. Parašykite refunds@testedroutes.com nurodydami užsakymo numerį. Visos detalės mūsų pinigų grąžinimo politikoje.",
      },
    ],
    youMightAlsoLike: "Taip pat gali patikti",
    bottomLine1: "Keliaukite daugiau.",
    bottomLine2: "Gaiškite mažiau laiko planavimui.",
    bottomBody:
      "Aukščiausios kokybės gidai, gimę iš 15 metų savarankiškų kelionių po 140 šalių.",
    bottomTagline: "DI ten nebuvo. Aš buvau.",
    bottomFooter: "PDF · Atsisiuntimas iškart · 30 dienų grąžinimas",
    getGuide: "Gauti gidą",
    comingSoonBtn: "Netrukus",
    pdfGuideLabel: "PDF gidas",
    instantDownload: "Atsisiuntimas iškart",
    pdfInstantDownload: "PDF · Atsisiuntimas iškart",
    getLinksFree: "Gauti nuorodas nemokamai",
    refunds: "30 dienų pinigų grąžinimas, be klausimų.",
    readPolicy: "Skaityti politiką",
    openBookingsOne: "Taip pat atidaryti mano rezervacijos nuorodą (viešbutis, transportas)",
    openBookingsMany: "Taip pat atidaryti mano {count} rezervacijų nuorodas (viešbutis, transportas)",
    trust: [
      { label: "Be rizikos", rest: "30 dienų pilnas grąžinimas" },
      { label: "Vienkartinis pirkimas", rest: "Jokios prenumeratos" },
      { label: "Veikia be interneto", rest: "Išsaugokite telefone" },
    ],
  },
};
export default lt;
