/**
 * One day's analytics, materialised.
 *
 * Written every night by /api/cron/analytics-rollup, which queries PostHog,
 * Polar, Sentry and Search Console and stores the answers here. Nothing in
 * these documents is authored by a human, and nothing should be — the
 * nightly job owns them completely and rewrites a day wholesale if it is
 * re-run.
 *
 * Why store the rollup at all, rather than re-querying the sources every
 * time the dashboard is opened:
 *
 *   - Retention. PostHog's plan ages events out; a rollup keeps the shape
 *     of a launch month readable years later at a few kilobytes a day.
 *   - Reproducibility. The morning agent's commentary can be checked
 *     against the exact numbers it saw, instead of numbers that have since
 *     been recomputed by four different APIs with four different lag
 *     characteristics.
 *   - Cost and speed. One HogQL query per night instead of one per page
 *     load, and the dashboard renders from a single small document.
 *
 * The `_id` is `analytics.YYYY-MM-DD` and the job uses createOrReplace, so
 * re-running a day is idempotent rather than additive. That differs from
 * the rule everywhere else in this dataset — content documents must be
 * patched field-by-field, because a createOrReplace over a doc someone has
 * edited in Studio silently discards their work. These are safe precisely
 * because no human writes them.
 */
export default {
  name: "analyticsSnapshot",
  title: "Analytics snapshot",
  type: "document",
  description:
    "Machine-written daily rollup. Generated by the nightly cron — do not hand-edit; the next run will overwrite it.",
  fields: [
    {
      name: "date",
      title: "Date",
      type: "date",
      description: "The UTC day these numbers describe.",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "generatedAt",
      title: "Generated at",
      type: "datetime",
      description: "When the rollup job ran. A late value means a retry.",
    },
    {
      name: "traffic",
      title: "Traffic",
      type: "object",
      fields: [
        { name: "pageviews", title: "Pageviews", type: "number" },
        { name: "guideViews", title: "Guide views", type: "number" },
        {
          name: "byCountry",
          title: "By country",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                { name: "country", type: "string" },
                { name: "count", type: "number" },
              ],
              preview: {
                select: { title: "country", subtitle: "count" },
              },
            },
          ],
        },
        {
          name: "bySource",
          title: "By source",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                { name: "source", type: "string" },
                { name: "count", type: "number" },
              ],
              preview: {
                select: { title: "source", subtitle: "count" },
              },
            },
          ],
        },
      ],
    },
    {
      name: "revenue",
      title: "Revenue (from Polar)",
      type: "object",
      description:
        "The authoritative money figures, read straight from Polar rather than inferred from webhooks. Refunded orders are excluded from the totals and counted separately — a day with one sale and one refund is not a zero day, and must not be reported as one.",
      fields: [
        {
          name: "orders",
          title: "Orders",
          type: "number",
          description: "Paid orders, excluding fully refunded ones.",
        },
        {
          name: "refunded",
          title: "Refunded",
          type: "number",
          description: "Orders refunded in this window.",
        },
        {
          name: "grossCents",
          title: "Gross (minor units)",
          type: "number",
          description:
            "What buyers paid, less any partial refunds. Divide by 100 to display.",
        },
        {
          name: "netCents",
          title: "Net (minor units)",
          type: "number",
          description:
            "What Polar remits after its merchant-of-record cut — the figure that reaches the bank. Always quote alongside gross; either one alone invites the wrong conclusion.",
        },
      ],
    },
    {
      name: "perGuide",
      title: "Per guide",
      type: "array",
      description:
        "The funnel, one row per guide. Views and checkout starts are both captured server-side, so the ratio between them is comparable — see app/api/e/route.js for why that matters.",
      of: [
        {
          type: "object",
          fields: [
            { name: "slug", title: "Slug", type: "string" },
            { name: "views", title: "Views", type: "number" },
            { name: "checkoutStarts", title: "Checkout starts", type: "number" },
            { name: "orders", title: "Orders", type: "number" },
            { name: "refunds", title: "Refunds", type: "number" },
            {
              name: "revenueCents",
              title: "Revenue (minor units)",
              type: "number",
              description:
                "Net of refunds that landed the same day, in cents to avoid float drift; divide by 100 to display. A refund arriving after its sale's day can't be netted here — use the top-level `revenue` block, read from Polar, whenever the money figure has to be exact.",
            },
            { name: "currency", title: "Currency", type: "string" },
          ],
          preview: {
            select: { title: "slug", subtitle: "orders" },
          },
        },
      ],
    },
    {
      name: "goLinks",
      title: "Go-link clicks",
      type: "array",
      description:
        "QR scans and short-link clicks. `kind: unknown` rows are printed slugs that resolve to nothing — each one is a paying reader who scanned a code and landed nowhere.",
      of: [
        {
          type: "object",
          fields: [
            { name: "slug", type: "string" },
            { name: "kind", type: "string" },
            { name: "clicks", type: "number" },
          ],
          preview: {
            select: { title: "slug", subtitle: "clicks" },
          },
        },
      ],
    },
    {
      name: "guideRequests",
      title: "Guide requests",
      type: "array",
      description:
        "Destinations visitors asked for on the homepage. The most direct demand signal the site produces for what to build next.",
      of: [
        {
          type: "object",
          fields: [
            { name: "destination", type: "string" },
            { name: "count", type: "number" },
          ],
          preview: {
            select: { title: "destination", subtitle: "count" },
          },
        },
      ],
    },
    {
      name: "newsletterSignups",
      title: "Newsletter signups",
      type: "number",
    },
    {
      name: "search",
      title: "Search Console",
      type: "object",
      description:
        "Google reports search data 2–3 days behind, so `date` here is NOT the snapshot's date — read `dataDate` before comparing it to anything else on the page.",
      fields: [
        { name: "dataDate", title: "Data date", type: "date" },
        { name: "clicks", title: "Clicks", type: "number" },
        { name: "impressions", title: "Impressions", type: "number" },
        {
          name: "topQueries",
          title: "Top queries",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                { name: "query", type: "string" },
                { name: "clicks", type: "number" },
                { name: "impressions", type: "number" },
                { name: "position", type: "number" },
              ],
              preview: { select: { title: "query", subtitle: "clicks" } },
            },
          ],
        },
        {
          name: "topPages",
          title: "Top pages",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                { name: "page", type: "string" },
                { name: "clicks", type: "number" },
                { name: "impressions", type: "number" },
              ],
              preview: { select: { title: "page", subtitle: "clicks" } },
            },
          ],
        },
      ],
    },
    {
      name: "errors",
      title: "Errors",
      type: "object",
      fields: [
        { name: "newIssues", title: "New Sentry issues", type: "number" },
        {
          name: "topIssues",
          title: "Top issues",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                { name: "title", type: "string" },
                { name: "count", type: "number" },
                { name: "url", type: "url" },
              ],
              preview: { select: { title: "title", subtitle: "count" } },
            },
          ],
        },
      ],
    },
    {
      name: "sourceErrors",
      title: "Source errors",
      type: "array",
      description:
        "Anything that makes this snapshot less than fully trustworthy: an upstream API that failed, or a mismatch between Polar's own order count and the one the webhooks recorded. A snapshot with entries here is partial, and the dashboard must say so rather than render the gaps as zeroes — an unmeasured day and a dead day look identical once they are both drawn as a flat line.",
      of: [{ type: "string" }],
    },
  ],
  orderings: [
    {
      title: "Newest first",
      name: "dateDesc",
      by: [{ field: "date", direction: "desc" }],
    },
  ],
  preview: {
    select: { date: "date", orders: "traffic.pageviews" },
    prepare({ date, orders }) {
      return {
        title: date || "(no date)",
        subtitle: typeof orders === "number" ? `${orders} pageviews` : "—",
      };
    },
  },
};
